runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: newblog.app

libraries:
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- name: PIL
  version: "1.1.7"
